# Workflow pour le backend
name: Backend CI # on peut déclencher le workflow lorsqu'on fait une pull request

# Événements pour déclencher le workflow
on: # on peut déclencher le workflow manuellement ou automatiquement
  push: # on peut déclencher le workflow lorsqu'on pousse du code sur le repository
    branches:
      - main # on peut déclencher le workflow lorsqu'on pousse du code sur le repository
  pull_request: # on peut déclencher le workflow lorsqu'on fait une pull request
    branches:
      - main # on peut déclencher le workflow lorsqu'on fait une pull request

jobs: # on peut déclencher le workflow lorsqu'on fait une pull request
  test-and-build: # on peut déclencher le workflow lorsqu'on fait une pull request
    runs-on: ubuntu-latest

    steps: # on peut déclencher le workflow lorsqu'on fait une pull request
      - name: Checkout code # on peut déclencher le workflow lorsqu'on fait une pull request
        uses: actions/checkout@v4 # on peut déclencher le workflow lorsqu'on fait une pull request

      - name: Setup Node.js # on peut déclencher le workflow lorsqu'on fait une pull request
        uses: actions/setup-node@v4 # on peut déclencher le workflow lorsqu'on fait une pull request
        with:
          node-version: "20" # on peut déclencher le workflow lorsqu'on fait une pull request
          cache: npm # on peut déclencher le workflow lorsqu'on fait une pull request

      - name: Install dependencies # on peut déclencher le workflow lorsqu'on fait une pull request
        run: npm ci # on peut déclencher le workflow lorsqu'on fait une pull request

      - name: Run tests # on peut déclencher le workflow lorsqu'on fait une pull request
        run: npm run test # on peut déclencher le workflow lorsqu'on fait une pull request

      - name: Build project # on peut déclencher le workflow lorsqu'on fait une pull request
        run: npm run build # on peut déclencher le workflow lorsqu'on fait une pull request
